### ISSUE TITLE
Does not work correctly with country groupings

### ISSUE THREAD

**Issue by theresakhoo** [krakenjs/file-resolver#28]
For example, str = 'es_CLAC_B' should resolve to
lang='es'
country='CLAC_B'

**Comment by grawk** [comment]
Hi Theresa,

Since CLAC_B isn't a standard country string, we shouldn't need to support it in file-resolver. However, you can still use file-resolver to resolve country groups like this. If you pass in an object to `parseLangTag`, the function will simply return the object.
E.g. pass in `{ country: 'CLAC_B', language: 'es', locale: 'es_CLAC_B' }` and `parseLangTag` will simply return it.
